import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "@/components/nav/Nav";
import Bottom from "@/components/bottom/Bottom";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} style={{maxWidth:"1600px", margin:"0 auto"}}>
        <section><Nav/></section>
        <section className=" ">{children}</section>
        <section><Bottom/></section>
        
        </body>
    </html>
  );
}
